"""empty message

Revision ID: b2471723b2b0
Revises: 14e21847fc3e
Create Date: 2021-08-25 13:31:23.627510

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b2471723b2b0'
down_revision = '14e21847fc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              existing_type=sa.FLOAT(),
                              nullable=True,
                              server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('fallback_value',
                              existing_type=sa.FLOAT(),
                              nullable=False,
                              server_default='16')

    # ### end Alembic commands ###
